export const products = [
   {
      id: 1,
      name: "Modern Sofa",
      category: "Chair",
      price: 499.99,
      rating: 4,
      image: "product-1.png",
      description: "A stylish and comfortable modern sofa for your living room.",
   },
   {
      id: 2,
      name: "Modern Sofa",
      category: "Chair",
      price: 49.99,
      rating: 5,
      image: "product-1.png",
      description: "A stylish and comfortable modern sofa for your living room.",
   },
   {
      id: 3,
      name: "Modern ebSofa",
      category: "Chair",
      price: 4987.99,
      rating: 4,
      image: "product-1.png",
      description: "A stylish and comfortable modern sofa for your living room.",
   },
   {
      id: 4,
      name: "Modern4e Sofa",
      category: "Chair",
      price: 899.99,
      rating: 3,
      image: "product-1.png",
      description: "A stylish and comfortable modern sofa for your living room.",
   },
   {
      id: 5,
      name: "Moderng Sofa",
      category: "Chair",
      price: 4656.99,
      rating: 4,
      image: "product-1.png",
      description: "A stylish and comfortable modern sofa for your living room.",
   },

   {
      id: 6,
      name: "Dining Table Set",
      category: "Beds",
      price: 799.99,
      rating: 5,
      image: "product-2.png",
      description: "A beautiful dining table set for family gatherings.",
   },
   {
      id: 7,
      name: "Dining Table Set",
      category: "Beds",
      price: 799.99,
      rating: 5,
      image: "product-2.png",
      description: "A beautiful dining table set for family gatherings.",
   },
   {
      id: 8,
      name: "Dining Table Set",
      category: "Beds",
      price: 799.99,
      rating: 5,
      image: "product-2.png",
      description: "A beautiful dining table set for family gatherings.",
   },
   {
      id: 9,
      name: "Dining Table Set",
      category: "Beds",
      price: 799.99,
      rating: 5,
      image: "product-2.png",
      description: "A beautiful dining table set for family gatherings.",
   },
   {
      id: 10,
      name: "Dining Table Set",
      category: "Beds",
      price: 799.99,
      rating: 5,
      image: "product-2.png",
      description: "A beautiful dining table set for family gatherings.",
   },

   {
      id: 11,
      name: "Office Chair",
      category: "Sofas",
      price: 199.99,
      rating: 4,
      image: "product-3.png",
      description: "An ergonomic office chair for your workspace.",
   },
   {
      id: 12,
      name: "Office Chair",
      category: "Sofas",
      price: 199.99,
      rating: 3,
      image: "product-3.png",
      description: "An ergonomic office chair for your workspace.",
   },
   {
      id: 13,
      name: "Office Chair",
      category: "Sofas",
      price: 199.99,
      rating: 3,
      image: "product-3.png",
      description: "An ergonomic office chair for your workspace.",
   },
   {
      id: 14,
      name: "Office Chair",
      category: "Sofas",
      price: 199.99,
      rating: 1,
      image: "product-3.png",
      description: "An ergonomic office chair for your workspace.",
   },
   {
      id: 15,
      name: "Office Chair",
      category: "Sofas",
      price: 199.99,
      rating: 3,
      image: "product-3.png",
      description: "An ergonomic office chair for your workspace.",
   },

   {
      id: 16,
      name: "Office Chair",
      category: "Lamp",
      price: 199.99,
      rating: 2,
      image: "product-4.png",
      description: "An ergonomic office chair for your workspace.",
   },
   {
      id: 17,
      name: "Office Chair",
      category: "Lamp",
      price: 199.99,
      rating: 5,
      image: "product-4.png",
      description: "An ergonomic office chair for your workspace.",
   },
   {
      id: 18,
      name: "Office Chair",
      category: "Lamp",
      price: 199.99,
      rating: 2,
      image: "product-4.png",
      description: "An ergonomic office chair for your workspace.",
   },
   {
      id: 19,
      name: "Office Chair",
      category: "Lamp",
      price: 199.99,
      rating: 3,
      image: "product-4.png",
      description: "An ergonomic office chair for your workspace.",
   },
   {
      id: 20,
      name: "ada Chair",
      category: "Lamp",
      price: 199.99,
      rating: 2,
      image: "product-4.png",
      description: "An ergonomic office chair for your workspace.",
   },
]